name: Ruby

on:
  push: []
  pull_request: []

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2.2'
          - 'head'
        os:
          - ubuntu-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
